name: daily-traffic-data-fetching


on:
  schedule:
  - cron:  '*/5 * * * *'

jobs:
  fetch-traffics:
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install
      working-directory: ./backend
      run: npm install
    - name: fetch
      working-directory: ./backend
      run: node scripts/dailyGetTraffics.js
